// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGVgZztY4uGoMsPlUHhqxriYDfgJyEwNg',
    appId: '1:970105539781:web:8d0279116996b2980274ac',
    messagingSenderId: '970105539781',
    projectId: 'musicstorevr-aa200',
    authDomain: 'musicstorevr-aa200.firebaseapp.com',
    storageBucket: 'musicstorevr-aa200.appspot.com',
    measurementId: 'G-N4RFY8T0N6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoZQJFwcOmnt52KwxatSSBPAa1mQuxrIQ',
    appId: '1:970105539781:android:792c1bd36e351d890274ac',
    messagingSenderId: '970105539781',
    projectId: 'musicstorevr-aa200',
    storageBucket: 'musicstorevr-aa200.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLKoCDBhqQYgAkIofr4CVBIosptAwLvbU',
    appId: '1:970105539781:ios:a489c1909aad21bd0274ac',
    messagingSenderId: '970105539781',
    projectId: 'musicstorevr-aa200',
    storageBucket: 'musicstorevr-aa200.appspot.com',
    iosBundleId: 'com.sinasys.officeFurnitureStore',
  );
}
